<?php
use Wvpn\Client\WebService;

/**
 * @file
 * Code for the Server feature.
 */
include_once 'server.features.inc';

/**
 * Implements hook_menu().
 */
function server_menu() {
  $items = array();

  $items['admin/config/watervpn'] = array(
    'title' => t('WaterVPN'),
    'description' => 'Watervpn settings and maintenances.',
    'position' => 'left',
    'weight' => 0,
    'page callback' => 'server_test_page',
    'access arguments' => array('access administration pages'),
  );

  $items['admin/config/watervpn/servers'] = array(
    'title' => t('Maintenances'),
    'description' => 'Update servers status.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('server_update_servers_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'server.batch.inc',
    'weight' => -20,
  );

  return $items;
}

function server_test_page() {

//   $server = node_load(23);

//   // Make sure we have radius service available.
//   $openvpn = WebService::getServiceClient('openvpn');
//   $host = $server->field_server_name[LANGUAGE_NONE][0]['value'];

//   try{
//     $response = $openvpn->getServerStatus($host);

//     // We have a this user in raidus db.
//     if ($response->getStatusCode() == 200) {

//       dsm($response->json());

//       // Update server node's load.
//       // server status high. tid 15. over 75% compacity.

//       // server status normal. tid 14. between 30% to 75% compacity.

//       // server status low. tid 16.  below 30% compacity.

//       // server status recommended. tid 13. below 20% compacity.
//       //       $server->field_server_load[LANGUAGE_NONE][0]['tid'] = 13;




//       $server_response = $response->json();

//       $download_avail = $server_response['download_avail'];

//       $download = $server_response['download'];

//       if ($download / $download_avail < 0.2) {
//         $server->field_server_load[LANGUAGE_NONE][0]['tid'] = 13;
//       }


//       // Server is up. tid 17.
//       $server->field_server_status[LANGUAGE_NONE][0]['tid'] = 17;
//     }
//     else {
//       // Update server node's status.
//       // If no respond from web service then we assume server went down. tid 24.
//       $server->field_server_status[LANGUAGE_NONE][0]['tid'] = 24;
//     }

//     node_save($server);
//   }
//   catch(GuzzleHttp\Exception\ClientException $e){
//     watchdog('server', "ErrorCode: [{$e->getCode()}] Message: [{$e->getMessage()}]");
//   }

  return '';
}

/**
 * Implements hook_node_view().
 */
function server_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'server' && $view_mode == 'teaser') {

    $arg0 = arg(0);
    // Load radius node from url.
    if (!empty($arg0) && $arg0 == 'servers') {
      $radius_node = node_load(arg(1));
      global $user;

      $path =  '/download/' . $radius_node->nid . '/' . $node->nid . '/' . $user->uid;
      $options = array(
      	'html' => FALSE,
        'attributes' => array(
      	  'class' => array('button', 'download'),
        ),
        'query' => drupal_get_destination(),
      );

      $links = array(l(t('Download Config File'), $path, $options));

      $node->content['buttons'] = array (
        '#markup' => theme('download_link', array('links' => $links)),
        '#weight' => 3,
      );
    }
  }
}

/**
 * Implements hook_field_extra_fields().
 * If we only invoke hook_node_view it won't work.
 * We have to implement this method, since we are using DS(display suite)
 * DS only cares about node_view stuff if those fields are exposed in the field UI
 */
function server_field_extra_fields() {
  $extra = array();
  // Just adding the psuedo field to the page node type.
  $extra['node']['server']['display'] = array(
    'buttons' => array(
      'label' => t('Buttons'),
      'description' => t('Buttons'),
      'weight' => -5,
    ),
  );
  return $extra;
}


/**
 * Implements hook_theme().
 */
function server_theme($existing, $type, $theme, $path) {
  return array(
    'download_link' => array(
    )
  );
}

/**
 * Create the unorder list.
 * @param array $vars variables passed by theme() function.
 * @return string
 */
function theme_download_link($vars) {
  $list_item = '';

  if (!empty($vars['links'])) {
    foreach ($vars['links'] as $link) {
      $list_item .= '<li>' . $link . '</li>';
    }
  }

  return '<ul class="buttons-group">' . $list_item . '</ul>';
}



/**
 * Get all server nodes from db.
 * @return mixed
 *  array contains server node ids or FALSE when failed.
 */
function server_get_server_nodes() {
  // Query all server nodes.
  $query = db_select('node', 'n')
  ->fields('n', array('nid'))
  ->condition('n.type', 'server');

  $server_nodes = $query->execute()->fetchAll();

  return !empty($server_nodes) ? $server_nodes : FALSE;
}

/**
 * The batch process function for server node type,
 * This function need to be in the module file, don't put it in
 * the server.batch.inc file, or it will failed silently.
 * @param unknown $server_nodes
 * @param unknown $context
 */
function server_process_server_nodes($server_nodes, &$context) {
  // How many server nodes we want to process each time.
  $limit = 5;

  // Update server nodes status.
  if (!isset($context['sandbox']['progress'])) {
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['title'] = '';
    $context['sandbox']['max'] = count($server_nodes);
    // The starting point the the array.
    $start = 0;
  }
  else {
    $start = $context['sandbox']['progress'];
  }

  // Only take a chunk of the nodes to process at a time.
  $server_nodes_section = array_slice($server_nodes, $start, $limit);

  // Process them.
  if($context['sandbox']['progress'] < $context['sandbox']['max']){

    foreach ($server_nodes_section as $server_node) {
      // TODO Update server nodes contents here.
      server_update_node($server_node->nid);

      // Have to keep track of progress, or we end up in a infinity loop.
      $context['sandbox']['progress']++;
      $context['results'][] = check_plain($node->title); // Keep a running tab of all of the nodes created.
      $context['message'] = $context['sandbox']['progress'] . " of " . $context['sandbox']['max'];
    }
  }

  // Check if the batch is finished
  if ($context['sandbox']['progress'] < $context['sandbox']['max']) {
    $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
  }
}

/**
 * Programatically update server node's properties.
 */
function server_update_node($nid) {
  $node = node_load($nid);
  if ($node->type == 'server') {
    // Make sure we have radius service available.
    $openvpn = WebService::getServiceClient('openvpn');
    $host = $node->field_server_name[LANGUAGE_NONE][0]['value'];

    try{
      $response = $openvpn->getServerStatus($host);

      // We have a this user in raidus db.
      if ($response->getStatusCode() == 200) {
        $server_response = $response->json();
        $download_avail = $server_response['download_avail'];
        $download = $server_response['download'];
        $upload_avail = $server_response['upload_avail'];
        $upload = $server_response['upload'];

        $current_dl_compacity = $download / $download_avail;
        $current_ul_compacity = $upload / $upload_avail;

        $current_compacity = ($current_dl_compacity + $current_ul_compacity) / 2;

        // Update server node's load.
        // server status high. tid 15. greater 75% compacity.
        if ($current_compacity > 0.75 ) {
          $server->field_server_load[LANGUAGE_NONE][0]['tid'] = 15;
        }

        // server status normal. tid 14. between 30% to 75% compacity.
        if ($current_compacity > 0.3 && $current_compacity < 0.75) {
          $server->field_server_load[LANGUAGE_NONE][0]['tid'] = 14;
        }

        // server status low. tid 16.  below 30% compacity.
        if ($current_compacity < 0.3) {
          $server->field_server_load[LANGUAGE_NONE][0]['tid'] = 16;
        }

        // server status recommended. tid 13. below 20% compacity.
        if ($current_compacity < 0.2) {
          $server->field_server_load[LANGUAGE_NONE][0]['tid'] = 13;
        }

        // Server is up. tid 17.
        $node->field_server_status[LANGUAGE_NONE][0]['tid'] = 17;
      }
      else {
        // Update server node's status.
        // If no respond from web service then we assume server went down. tid 24.
        $node->field_server_status[LANGUAGE_NONE][0]['tid'] = 24;
      }

      node_save($node);
    }
    catch(GuzzleHttp\Exception\ClientException $e){
      watchdog('server', "ErrorCode: [{$e->getCode()}] Message: [{$e->getMessage()}]");
    }
  }
}

/**
 * Implements hook_cron().
 */
function server_cron() {
  $server_nodes = server_get_server_nodes();
  $queue = DrupalQueue::get('servers');
  foreach($server_nodes as $server_node) {
    $queue->createItem($server_node->nid);
  }

  /**
   * Exception 200 status code
   */
  $openvpn  = WebService::getServiceClient('openvpn');
  $async    = 'true';
  try{
    $response = $openvpn->fetchServerStatusJob($async);
  }
  catch( GuzzleHttp\Exception\ClientException $e){
    echo "ErrorCode: [{$e->getCode()}] Message: [{$e->getMessage()}]";
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function server_cron_queue_info() {
  $queues['servers'] = array(
    'worker callback' => 'server_queue_run', // The callback function for each queue item.
    'time' => 60, // The max run time per cron run in seconds.
  );
  return $queues;
}

/**
 * The callback function for each queue item
 * @param $nid node id.
 */
function server_queue_run($nid) {
  server_update_node($nid);
}