<?php

/**
 * Implements hook_block_info().
 */
function login_block_block_info() {
  $blocks['user_login_block'] = array(
    'info' => t('User Login Logout'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function login_block_block_view($delta = '') {
  $block = array();

  switch ($delta) {
  	case 'user_login_block':
  	  $block['subject'] = '';
  	  $block['content'] = _login_block_content();
  	  break;
  }

  return $block;
}

/**
 * Supply content
 */
function _login_block_content() {
  if (user_is_logged_in()) {
    global $user;

    //wrapper user entity for easy data access
    $wrapper = entity_metadata_wrapper('user', $user);
    
    if (isset($wrapper->field_first_name)) {
      $name = $wrapper->field_first_name->value();
    }
    else {
      $name = 'haha';
    }


    if (!$name) {
      $name = $user->name;
    }

    return theme('login_block', array(
      'uid' => $user->uid,
      'name' => check_plain($name),
    ));
  }
  else {
    $help_page = variable_get('login_block_help_page', '');
    return theme('login_block', array(
      'login_url' => url('user/login', array('query' => drupal_get_destination())),
      'register_url' => $help_page ? url($help_page, array('query' => drupal_get_destination())) : url('user/register', array('query' => drupal_get_destination())),
    ));
  }
}